linters-settings:
    errcheck:
        exclude: ./.errcheck_excludes.txt

issues:
    # TODO: move away from deprecated prometheus.InstrumentHandler{,Func}
    - linters:
          - staticcheck
      text: "SA1019:"
