linters-settings:
    errcheck:
        exclude: ./.errcheck_excludes.txt

issues:
    exclude-rules:
        # TODO: move away from deprecated prometheus.InstrumentHandler{,Func}
        - linters:
              - staticcheck
          text: "SA1019:"
